# fly.toml app configuration file generated for kakeibo-weathered-shape-5200 on 2026-04-13T23:28:08+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'kakeibo-weathered-shape-5200'
primary_region = 'nrt'
console_command = '/rails/bin/rails console'

[build]

[env]
  PORT = '8080'

[processes]
  app = './bin/rails server'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'suspend'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

  [[http_service.checks]]
    interval = '10s'
    timeout = '2s'
    grace_period = '5s'
    method = 'GET'
    path = '/up'
    protocol = 'http'
    tls_skip_verify = false

    [http_service.checks.headers]
      X-Forwarded-Proto = 'https'

[[vm]]
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 256
